export const ADD_ADRESS = 'ADD_ADRESS';
export const ADD_MAP_ARRAY = 'ADD_MAP_ARRAY';
export const CHANGE_LIST_ARRAY = 'CHANGE_LIST_ARRAY';
export const DELETE_ROUTE_LIST = 'DELETE_ROUTE_LIST';
export const CHANGE_ROUTE_LIST_ARRAY = 'CHANGE_ROUTE_LIST_ARRAY';
export const CHANGE_ADDRESS_INFO = 'CHANGE_ADDRESS_INFO';